[install]
minimumReleaseAge = 604800
minimumReleaseAgeExcludes = ["devalue", "nuxt", "@nuxt/kit", "@nuxt/nitro-server", "@nuxt/schema", "@nuxt/vite-builder", "vue", "vue-router", "ws"]
auto = "disable"
frozenLockfile = true
saveTextLockfile = true
exact = true
